version: '3.9'
services:
  nginx:
    image: nginx
    ports:
      - '5000:80'
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
  # environment:
  #  - NGINX_HOST=foobar.com
  #  - NGINX_PORT=80

  api:
    image: abbaslamouri/lightmylamp-api
    deploy:
      replicas: 4
      restart_policy:
        delay: 5s
      update_config:
        parallelism: 2
        delay: 10s
    build: .
    # ports:
    #   - 5000:4000
    # volumes:
    # - ./:/app
    # - /app/node_modules
    # - /app/dist
    # environment:
    # DB_USER: lightmylamp-db-user
    # DB_PASSWORD: Wjshg^&JXslsp
    # DB_NAME: lightmylamp
    # DB_URL: mongodb://mongo_db:27017
    env_file:
      - ./.env
    depends_on:
      - db
      - nginx

  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
    # restart: always
    # ports:
    # - 2717:27017
    volumes:
      - mongo-db:/data/db

  # redis:
  #   image: redis
  # ports:
  #   - 6379:6379

volumes:
  mongo-db: {}
