version: '3.9'
services:
  # mongo_db:
  #   image: mongo:latest
  #   restart: always
  #   ports:
  #     - 2717:27017
  #   volumes:
  #     - mongo_db:/data/db
  api:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist
    # environment:
    #   PORT: 5000
    #   DB_NAME: api-ts
    #   DB_URL: mongodb://mongo_db:27017
    env_file:
      - ./.env
    # depends_on:
    #   - mongo_db
# volumes:
#   mongo_db: {}
