version: '3.9'
services:
  # mongo_db:
  #   image: mongo:latest
  #   restart: always
  #   ports:
  #     - 2717:27017
  #   volumes:
  #     - mongo_db:/data/db
  api:
    deploy:
      mode: replicated
      replicas: 8
      restart_policy:
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
    build:
      context: .
      args:
        NODE_ENV: production
    # ports:
    # - 5000:5000
    # volumes:
    # - ./:/app
    #   - /app/node_modules
    # - /app/dist
    environment:
      - NODE_ENV=production
    # environment:
    #   PORT: 5000
    #   DB_NAME: api-ts
    #   DB_URL: mongodb://mongo_db:27017
    # env_file:
    # - ./.env
    # command: node dist/src/server.js

    # depends_on:
    #   - mongo_db
# volumes:
#   mongo_db: {}
