version: '3.9'
services:
  api:
    build: .
    ports:
      - 5000:5000
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    #   - /app/dist
    environment:
      DB_USER: lightmylamp-db-user
      DB_PASSWORD: Wjshg^&JXslsp
      # DB_NAME: lightmylamp
      # DB_URL: mongodb://mongo_db:27017
    # env_file:
    # - ./.env
    depends_on:
      - db

  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: lightmylamp-db-user
      MONGO_INITDB_ROOT_PASSWORD: Wjshg^&JXslsp
    # restart: always
    # ports:
    # - 2717:27017
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: {}
